/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi1;

/**
 *
 * @author HP
 */
public class Adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form quetion
     */
    public Adminpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1btn = new javax.swing.ButtonGroup();
        Q2btn = new javax.swing.ButtonGroup();
        Q3btn = new javax.swing.ButtonGroup();
        Q4btn = new javax.swing.ButtonGroup();
        Q5btn = new javax.swing.ButtonGroup();
        Q6btn = new javax.swing.ButtonGroup();
        Q7btn = new javax.swing.ButtonGroup();
        Q8btn = new javax.swing.ButtonGroup();
        back = new javax.swing.JPanel();
        Q_Center = new javax.swing.JPanel();
        opt1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        opt2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        opt3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnanaly = new javax.swing.JButton();
        btndat = new javax.swing.JButton();
        btndat1 = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        back.setBackground(new java.awt.Color(255, 102, 102));

        Q_Center.setBackground(new java.awt.Color(255, 204, 204));
        Q_Center.setLayout(new java.awt.CardLayout());

        opt1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setText("Analytics");

        javax.swing.GroupLayout opt1Layout = new javax.swing.GroupLayout(opt1);
        opt1.setLayout(opt1Layout);
        opt1Layout.setHorizontalGroup(
            opt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
        );
        opt1Layout.setVerticalGroup(
            opt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        Q_Center.add(opt1, "card2");

        opt2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setText("Data");

        javax.swing.GroupLayout opt2Layout = new javax.swing.GroupLayout(opt2);
        opt2.setLayout(opt2Layout);
        opt2Layout.setHorizontalGroup(
            opt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        opt2Layout.setVerticalGroup(
            opt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        Q_Center.add(opt2, "card2");

        opt3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setText("Data2");

        javax.swing.GroupLayout opt3Layout = new javax.swing.GroupLayout(opt3);
        opt3.setLayout(opt3Layout);
        opt3Layout.setHorizontalGroup(
            opt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt3Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        opt3Layout.setVerticalGroup(
            opt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opt3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        Q_Center.add(opt3, "card2");

        btnanaly.setText("Analytics");
        btnanaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalyActionPerformed(evt);
            }
        });

        btndat.setText("Data");
        btndat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatActionPerformed(evt);
            }
        });

        btndat1.setText("Data1");
        btndat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndat1ActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Q_Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnanaly, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(btndat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndat1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(34, 34, 34))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnanaly)
                    .addComponent(btndat)
                    .addComponent(btndat1))
                .addGap(32, 32, 32)
                .addComponent(Q_Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnanalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalyActionPerformed
        // TODO add your handling code here:
        opt1.setVisible(true);
        opt2.setVisible(false);
        opt3.setVisible(false);
        
    }//GEN-LAST:event_btnanalyActionPerformed

    private void btndatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatActionPerformed
        // TODO add your handling code here:
        opt2.setVisible(true);
        opt1.setVisible(false);
        opt3.setVisible(false);;
    }//GEN-LAST:event_btndatActionPerformed

    private void btndat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndat1ActionPerformed
        // TODO add your handling code here:
        opt3.setVisible(true);
        opt1.setVisible(false);
        opt2.setVisible(false);
    }//GEN-LAST:event_btndat1ActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        Admin s = new Admin();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlogoutActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Q1btn;
    private javax.swing.ButtonGroup Q2btn;
    private javax.swing.ButtonGroup Q3btn;
    private javax.swing.ButtonGroup Q4btn;
    private javax.swing.ButtonGroup Q5btn;
    private javax.swing.ButtonGroup Q6btn;
    private javax.swing.ButtonGroup Q7btn;
    private javax.swing.ButtonGroup Q8btn;
    private javax.swing.JPanel Q_Center;
    private javax.swing.JPanel back;
    private javax.swing.JButton btnanaly;
    private javax.swing.JButton btndat;
    private javax.swing.JButton btndat1;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel opt1;
    private javax.swing.JPanel opt2;
    private javax.swing.JPanel opt3;
    // End of variables declaration//GEN-END:variables
}
