/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi1;

/**
 *
 * @author HP
 */
public class quetion extends javax.swing.JFrame {

    /**
     * Creates new form quetion
     */
    public quetion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1btn = new javax.swing.ButtonGroup();
        Q2btn = new javax.swing.ButtonGroup();
        Q3btn = new javax.swing.ButtonGroup();
        Q4btn = new javax.swing.ButtonGroup();
        Q5btn = new javax.swing.ButtonGroup();
        Q6btn = new javax.swing.ButtonGroup();
        Q7btn = new javax.swing.ButtonGroup();
        Q8btn = new javax.swing.ButtonGroup();
        back = new javax.swing.JPanel();
        Q_Center = new javax.swing.JPanel();
        q1 = new javax.swing.JPanel();
        Q1nextbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Q1rdo1 = new javax.swing.JRadioButton();
        Q1rdo2 = new javax.swing.JRadioButton();
        Q1rdo3 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Q2rdo1 = new javax.swing.JRadioButton();
        Q2rdo2 = new javax.swing.JRadioButton();
        Q2nxt = new javax.swing.JButton();
        Q2bck = new javax.swing.JButton();
        q3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Q3rdo1 = new javax.swing.JRadioButton();
        Q3rdo2 = new javax.swing.JRadioButton();
        Q3bck = new javax.swing.JButton();
        Q3nxt = new javax.swing.JButton();
        q4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Q4rdo1 = new javax.swing.JRadioButton();
        Q4rdo2 = new javax.swing.JRadioButton();
        Q4rdo3 = new javax.swing.JRadioButton();
        Q4rdo4 = new javax.swing.JRadioButton();
        Q4bck = new javax.swing.JButton();
        Q4nxt = new javax.swing.JButton();
        q5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Q5rdo1 = new javax.swing.JRadioButton();
        Q5rdo2 = new javax.swing.JRadioButton();
        Q5rdo3 = new javax.swing.JRadioButton();
        Q5rdo4 = new javax.swing.JRadioButton();
        Q5rdo5 = new javax.swing.JRadioButton();
        Q5bck = new javax.swing.JButton();
        Q5nxt = new javax.swing.JButton();
        q6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        Q6bck = new javax.swing.JButton();
        Q6nxt = new javax.swing.JButton();
        q7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Q7rdo1 = new javax.swing.JRadioButton();
        Q7rdo2 = new javax.swing.JRadioButton();
        Q7rdo3 = new javax.swing.JRadioButton();
        Q7bck = new javax.swing.JButton();
        Q7nxt = new javax.swing.JButton();
        q8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Q8rdo1 = new javax.swing.JRadioButton();
        Q8rdo2 = new javax.swing.JRadioButton();
        Q8rdo3 = new javax.swing.JRadioButton();
        Q8bck = new javax.swing.JButton();
        Q8nxt = new javax.swing.JButton();
        q9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Q9rdo1 = new javax.swing.JRadioButton();
        Q9rdo2 = new javax.swing.JRadioButton();
        Q9bck = new javax.swing.JButton();
        Q9nxt = new javax.swing.JButton();
        q10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Q10rdo1 = new javax.swing.JRadioButton();
        Q10rdo2 = new javax.swing.JRadioButton();
        Q10rdo3 = new javax.swing.JRadioButton();
        Q10bck = new javax.swing.JButton();
        Q10sbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        back.setBackground(new java.awt.Color(255, 102, 102));

        Q_Center.setBackground(new java.awt.Color(255, 204, 204));
        Q_Center.setLayout(new java.awt.CardLayout());

        q1.setBackground(new java.awt.Color(255, 204, 204));

        Q1nextbtn.setBackground(new java.awt.Color(255, 102, 0));
        Q1nextbtn.setText("NEXT");
        Q1nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1nextbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("How do you get to know about Barista Pro?");

        Q1btn.add(Q1rdo1);
        Q1rdo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Q1rdo1.setText("Word of Mouth");

        Q1btn.add(Q1rdo2);
        Q1rdo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Q1rdo2.setText("Advertisements");

        Q1btn.add(Q1rdo3);
        Q1rdo3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Q1rdo3.setText("Social Media");

        javax.swing.GroupLayout q1Layout = new javax.swing.GroupLayout(q1);
        q1.setLayout(q1Layout);
        q1Layout.setHorizontalGroup(
            q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q1nextbtn)
                .addGap(78, 78, 78))
            .addGroup(q1Layout.createSequentialGroup()
                .addGroup(q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q1rdo2)
                            .addComponent(Q1rdo1)
                            .addComponent(Q1rdo3))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        q1Layout.setVerticalGroup(
            q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(Q1nextbtn)
                .addGap(33, 33, 33))
        );

        Q_Center.add(q1, "card2");

        q2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Are you feeling tired?");

        Q2btn.add(Q2rdo1);
        Q2rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q2rdo1.setText("YES");

        Q2btn.add(Q2rdo2);
        Q2rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q2rdo2.setText("NO");

        Q2nxt.setText("NEXT");
        Q2nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2nxtActionPerformed(evt);
            }
        });

        Q2bck.setText("BACK");
        Q2bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2bckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q2Layout = new javax.swing.GroupLayout(q2);
        q2.setLayout(q2Layout);
        q2Layout.setHorizontalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2Layout.createSequentialGroup()
                .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2))
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q2rdo2)
                            .addComponent(Q2rdo1))))
                .addContainerGap(717, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Q2bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q2nxt)
                .addGap(72, 72, 72))
        );
        q2Layout.setVerticalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Q2rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q2rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2nxt)
                    .addComponent(Q2bck))
                .addGap(26, 26, 26))
        );

        Q_Center.add(q2, "card2");

        q3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Is this your first visit?");

        Q3btn.add(Q3rdo1);
        Q3rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q3rdo1.setText("YES");

        Q3btn.add(Q3rdo2);
        Q3rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q3rdo2.setText("No, Already visited");

        Q3bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q3bck.setText("BACK");
        Q3bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3bckActionPerformed(evt);
            }
        });

        Q3nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q3nxt.setText("NEXT");
        Q3nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q3Layout = new javax.swing.GroupLayout(q3);
        q3.setLayout(q3Layout);
        q3Layout.setHorizontalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3Layout.createSequentialGroup()
                .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3))
                    .addGroup(q3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3rdo2)
                            .addComponent(Q3rdo1))))
                .addContainerGap(717, Short.MAX_VALUE))
            .addGroup(q3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Q3bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q3nxt)
                .addGap(52, 52, 52))
        );
        q3Layout.setVerticalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Q3rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q3rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q3bck)
                    .addComponent(Q3nxt))
                .addGap(30, 30, 30))
        );

        Q_Center.add(q3, "card2");

        q4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("What do you prefer to drink?");

        Q4btn.add(Q4rdo1);
        Q4rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4rdo1.setText("Cappuccino");

        Q4btn.add(Q4rdo2);
        Q4rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4rdo2.setText("Macchiato");

        Q4btn.add(Q4rdo3);
        Q4rdo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4rdo3.setText("Espresso");

        Q4btn.add(Q4rdo4);
        Q4rdo4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4rdo4.setText("Latte");

        Q4bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4bck.setText("BACK");
        Q4bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4bckActionPerformed(evt);
            }
        });

        Q4nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q4nxt.setText("NEXT");
        Q4nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q4Layout = new javax.swing.GroupLayout(q4);
        q4.setLayout(q4Layout);
        q4Layout.setHorizontalGroup(
            q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4Layout.createSequentialGroup()
                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q4Layout.createSequentialGroup()
                        .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q4Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel4))
                            .addGroup(q4Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Q4rdo2)
                                    .addComponent(Q4rdo1)
                                    .addComponent(Q4rdo3)
                                    .addComponent(Q4rdo4))))
                        .addGap(0, 659, Short.MAX_VALUE))
                    .addGroup(q4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Q4bck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q4nxt)))
                .addContainerGap())
        );
        q4Layout.setVerticalGroup(
            q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Q4rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q4rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q4rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q4rdo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q4bck)
                    .addComponent(Q4nxt))
                .addGap(24, 24, 24))
        );

        Q_Center.add(q4, "card2");

        q5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("What do you prefer as the topping?");

        Q5btn.add(Q5rdo1);
        Q5rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5rdo1.setText("Honey");

        Q5btn.add(Q5rdo2);
        Q5rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5rdo2.setText("Butter");

        Q5btn.add(Q5rdo3);
        Q5rdo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5rdo3.setText("Cardamom");

        Q5btn.add(Q5rdo4);
        Q5rdo4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5rdo4.setText("Chocolate");

        Q5btn.add(Q5rdo5);
        Q5rdo5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5rdo5.setText("Not at all");

        Q5bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5bck.setText("BACK");
        Q5bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5bckActionPerformed(evt);
            }
        });

        Q5nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q5nxt.setText("NEXT");
        Q5nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q5Layout = new javax.swing.GroupLayout(q5);
        q5.setLayout(q5Layout);
        q5Layout.setHorizontalGroup(
            q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5Layout.createSequentialGroup()
                .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q5Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel5))
                    .addGroup(q5Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q5rdo2)
                            .addComponent(Q5rdo1)
                            .addComponent(Q5rdo3)
                            .addComponent(Q5rdo4)
                            .addComponent(Q5rdo5))))
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(q5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Q5bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q5nxt)
                .addGap(58, 58, 58))
        );
        q5Layout.setVerticalGroup(
            q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Q5rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q5rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q5rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q5rdo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q5rdo5)
                .addGap(18, 18, 18)
                .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q5bck)
                    .addComponent(Q5nxt))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Q_Center.add(q5, "card2");

        q6.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("What is your preference in Latte art?");

        Q6btn.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton1.setText("Heart");

        Q6btn.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton2.setText("Rosetta");

        Q6btn.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton3.setText("Etch spirals");

        Q6btn.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton4.setText("Chocolate syrup circles");

        Q6btn.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton5.setText("Not at all");

        Q6bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q6bck.setText("BACK");
        Q6bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6bckActionPerformed(evt);
            }
        });

        Q6nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q6nxt.setText("NEXT");
        Q6nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q6Layout = new javax.swing.GroupLayout(q6);
        q6.setLayout(q6Layout);
        q6Layout.setHorizontalGroup(
            q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q6Layout.createSequentialGroup()
                .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q6Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel6))
                    .addGroup(q6Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(604, Short.MAX_VALUE))
            .addGroup(q6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Q6bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q6nxt)
                .addGap(53, 53, 53))
        );
        q6Layout.setVerticalGroup(
            q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addGap(62, 62, 62)
                .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q6bck)
                    .addComponent(Q6nxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Q_Center.add(q6, "card2");

        q7.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("What is your preference in Milk?");

        Q7btn.add(Q7rdo1);
        Q7rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q7rdo1.setText("Full cream");

        Q7btn.add(Q7rdo2);
        Q7rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q7rdo2.setText("Standardized");

        Q7btn.add(Q7rdo3);
        Q7rdo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q7rdo3.setText("No milk");

        Q7bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q7bck.setText("BACK");
        Q7bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7bckActionPerformed(evt);
            }
        });

        Q7nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q7nxt.setText("NEXT");
        Q7nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q7Layout = new javax.swing.GroupLayout(q7);
        q7.setLayout(q7Layout);
        q7Layout.setHorizontalGroup(
            q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7Layout.createSequentialGroup()
                .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7))
                    .addGroup(q7Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q7rdo2)
                            .addComponent(Q7rdo1)
                            .addComponent(Q7rdo3))))
                .addContainerGap(672, Short.MAX_VALUE))
            .addGroup(q7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Q7bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q7nxt)
                .addGap(55, 55, 55))
        );
        q7Layout.setVerticalGroup(
            q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Q7rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q7rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q7rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q7bck)
                    .addComponent(Q7nxt))
                .addGap(41, 41, 41))
        );

        Q_Center.add(q7, "card2");

        q8.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("What is your preference in sugar?");

        Q8rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q8rdo1.setText("Normal");

        Q8rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q8rdo2.setText("Moderate");

        Q8rdo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q8rdo3.setText("High");

        Q8bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q8bck.setText("BACK");
        Q8bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q8bckActionPerformed(evt);
            }
        });

        Q8nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q8nxt.setText("NEXT");
        Q8nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q8nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q8Layout = new javax.swing.GroupLayout(q8);
        q8.setLayout(q8Layout);
        q8Layout.setHorizontalGroup(
            q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8Layout.createSequentialGroup()
                .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q8Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8))
                    .addGroup(q8Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q8rdo2)
                            .addComponent(Q8rdo1)
                            .addComponent(Q8rdo3))))
                .addContainerGap(656, Short.MAX_VALUE))
            .addGroup(q8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Q8bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q8nxt)
                .addGap(35, 35, 35))
        );
        q8Layout.setVerticalGroup(
            q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(Q8rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q8rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q8rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q8bck)
                    .addComponent(Q8nxt))
                .addGap(36, 36, 36))
        );

        Q_Center.add(q8, "card2");

        q9.setBackground(new java.awt.Color(255, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("What type of delivery method you prefer?");

        Q9rdo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q9rdo1.setText("Dine inn");

        Q9rdo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q9rdo2.setText("Take away");

        Q9bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q9bck.setText("BACK");
        Q9bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q9bckActionPerformed(evt);
            }
        });

        Q9nxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q9nxt.setText("NEXT");
        Q9nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q9nxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q9Layout = new javax.swing.GroupLayout(q9);
        q9.setLayout(q9Layout);
        q9Layout.setHorizontalGroup(
            q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q9Layout.createSequentialGroup()
                .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q9Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9))
                    .addGroup(q9Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q9rdo2)
                            .addComponent(Q9rdo1))))
                .addContainerGap(584, Short.MAX_VALUE))
            .addGroup(q9Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Q9bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q9nxt)
                .addGap(76, 76, 76))
        );
        q9Layout.setVerticalGroup(
            q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q9Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(Q9rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q9rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q9bck)
                    .addComponent(Q9nxt))
                .addGap(40, 40, 40))
        );

        Q_Center.add(q9, "card2");

        q10.setBackground(new java.awt.Color(255, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("What type of payment method you prefer?");

        Q10rdo1.setText("Card");

        Q10rdo2.setText("Cash");

        Q10rdo3.setText("E-Wallets");

        Q10bck.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q10bck.setText("BACK");
        Q10bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q10bckActionPerformed(evt);
            }
        });

        Q10sbt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Q10sbt.setText("SUBMIT");

        javax.swing.GroupLayout q10Layout = new javax.swing.GroupLayout(q10);
        q10.setLayout(q10Layout);
        q10Layout.setHorizontalGroup(
            q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q10Layout.createSequentialGroup()
                .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q10Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10))
                    .addGroup(q10Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q10rdo2)
                            .addComponent(Q10rdo1)
                            .addComponent(Q10rdo3))))
                .addContainerGap(590, Short.MAX_VALUE))
            .addGroup(q10Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Q10bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q10sbt)
                .addGap(56, 56, 56))
        );
        q10Layout.setVerticalGroup(
            q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q10Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(Q10rdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q10rdo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q10rdo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q10bck)
                    .addComponent(Q10sbt))
                .addGap(32, 32, 32))
        );

        Q_Center.add(q10, "card2");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Q_Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(Q_Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Q1nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1nextbtnActionPerformed
        // TODO add your handling code here:
        
        q2.setVisible(true);
        q1.setVisible(false);
    }//GEN-LAST:event_Q1nextbtnActionPerformed

    private void Q2nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2nxtActionPerformed
        // TODO add your handling code here:
        q3.setVisible(true);
        q2.setVisible(false);
    }//GEN-LAST:event_Q2nxtActionPerformed

    private void Q2bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2bckActionPerformed
        // TODO add your handling code here:
        q1.setVisible(true);
        q2.setVisible(false);
    }//GEN-LAST:event_Q2bckActionPerformed

    private void Q3nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3nxtActionPerformed
        // TODO add your handling code here:
        q4.setVisible(true);
        q3.setVisible(false);
    }//GEN-LAST:event_Q3nxtActionPerformed

    private void Q3bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3bckActionPerformed
        // TODO add your handling code here:
        q2.setVisible(true);
        q3.setVisible(false);
    }//GEN-LAST:event_Q3bckActionPerformed

    private void Q4nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4nxtActionPerformed
        // TODO add your handling code here:
        q5.setVisible(true);
        q4.setVisible(false);
    }//GEN-LAST:event_Q4nxtActionPerformed

    private void Q4bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4bckActionPerformed
        // TODO add your handling code here:
        q3.setVisible(true);
        q4.setVisible(false);
    }//GEN-LAST:event_Q4bckActionPerformed

    private void Q5nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5nxtActionPerformed
        // TODO add your handling code here:
         q6.setVisible(true);
         q5.setVisible(false);
    }//GEN-LAST:event_Q5nxtActionPerformed
 
    private void Q6nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q6nxtActionPerformed
        // TODO add your handling code here:
         q7.setVisible(true);
         q6.setVisible(false);
    }//GEN-LAST:event_Q6nxtActionPerformed

    private void Q5bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5bckActionPerformed
        // TODO add your handling code here:
         q4.setVisible(true);
         q5.setVisible(false);
    }//GEN-LAST:event_Q5bckActionPerformed

    private void Q6bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q6bckActionPerformed
        // TODO add your handling code here:
         q5.setVisible(true);
         q6.setVisible(false);
        
    }//GEN-LAST:event_Q6bckActionPerformed

    private void Q7nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7nxtActionPerformed
        // TODO add your handling code here:
         q8.setVisible(true);
         q7.setVisible(false);
        
    }//GEN-LAST:event_Q7nxtActionPerformed

    private void Q7bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7bckActionPerformed
        // TODO add your handling code here:
         q6.setVisible(true);
         q7.setVisible(false);
    }//GEN-LAST:event_Q7bckActionPerformed

    private void Q8bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q8bckActionPerformed
        // TODO add your handling code here:
         q7.setVisible(true);
         q8.setVisible(false);
    }//GEN-LAST:event_Q8bckActionPerformed

    private void Q8nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q8nxtActionPerformed
        // TODO add your handling code here:
         q9.setVisible(true);
         q8.setVisible(false);
    }//GEN-LAST:event_Q8nxtActionPerformed

    private void Q10bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q10bckActionPerformed
        // TODO add your handling code here:
         q9.setVisible(true);
         q10.setVisible(false);
        
    }//GEN-LAST:event_Q10bckActionPerformed

    private void Q9bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q9bckActionPerformed
        // TODO add your handling code here:
         q8.setVisible(true);
         q10.setVisible(false);
    }//GEN-LAST:event_Q9bckActionPerformed

    private void Q9nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q9nxtActionPerformed
        // TODO add your handling code here:
         q10.setVisible(true);
         q9.setVisible(false);
    }//GEN-LAST:event_Q9nxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quetion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quetion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quetion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quetion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quetion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Q10bck;
    private javax.swing.JRadioButton Q10rdo1;
    private javax.swing.JRadioButton Q10rdo2;
    private javax.swing.JRadioButton Q10rdo3;
    private javax.swing.JButton Q10sbt;
    private javax.swing.ButtonGroup Q1btn;
    private javax.swing.JButton Q1nextbtn;
    private javax.swing.JRadioButton Q1rdo1;
    private javax.swing.JRadioButton Q1rdo2;
    private javax.swing.JRadioButton Q1rdo3;
    private javax.swing.JButton Q2bck;
    private javax.swing.ButtonGroup Q2btn;
    private javax.swing.JButton Q2nxt;
    private javax.swing.JRadioButton Q2rdo1;
    private javax.swing.JRadioButton Q2rdo2;
    private javax.swing.JButton Q3bck;
    private javax.swing.ButtonGroup Q3btn;
    private javax.swing.JButton Q3nxt;
    private javax.swing.JRadioButton Q3rdo1;
    private javax.swing.JRadioButton Q3rdo2;
    private javax.swing.JButton Q4bck;
    private javax.swing.ButtonGroup Q4btn;
    private javax.swing.JButton Q4nxt;
    private javax.swing.JRadioButton Q4rdo1;
    private javax.swing.JRadioButton Q4rdo2;
    private javax.swing.JRadioButton Q4rdo3;
    private javax.swing.JRadioButton Q4rdo4;
    private javax.swing.JButton Q5bck;
    private javax.swing.ButtonGroup Q5btn;
    private javax.swing.JButton Q5nxt;
    private javax.swing.JRadioButton Q5rdo1;
    private javax.swing.JRadioButton Q5rdo2;
    private javax.swing.JRadioButton Q5rdo3;
    private javax.swing.JRadioButton Q5rdo4;
    private javax.swing.JRadioButton Q5rdo5;
    private javax.swing.JButton Q6bck;
    private javax.swing.ButtonGroup Q6btn;
    private javax.swing.JButton Q6nxt;
    private javax.swing.JButton Q7bck;
    private javax.swing.ButtonGroup Q7btn;
    private javax.swing.JButton Q7nxt;
    private javax.swing.JRadioButton Q7rdo1;
    private javax.swing.JRadioButton Q7rdo2;
    private javax.swing.JRadioButton Q7rdo3;
    private javax.swing.JButton Q8bck;
    private javax.swing.ButtonGroup Q8btn;
    private javax.swing.JButton Q8nxt;
    private javax.swing.JRadioButton Q8rdo1;
    private javax.swing.JRadioButton Q8rdo2;
    private javax.swing.JRadioButton Q8rdo3;
    private javax.swing.JButton Q9bck;
    private javax.swing.JButton Q9nxt;
    private javax.swing.JRadioButton Q9rdo1;
    private javax.swing.JRadioButton Q9rdo2;
    private javax.swing.JPanel Q_Center;
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel q1;
    private javax.swing.JPanel q10;
    private javax.swing.JPanel q2;
    private javax.swing.JPanel q3;
    private javax.swing.JPanel q4;
    private javax.swing.JPanel q5;
    private javax.swing.JPanel q6;
    private javax.swing.JPanel q7;
    private javax.swing.JPanel q8;
    private javax.swing.JPanel q9;
    // End of variables declaration//GEN-END:variables
}
